version: '3.8'

services:
  web:
    build: .
    container_name: todo-app
    ports:
      - "8001:8000"
    volumes:
      # 개발 시 코드 변경사항 실시간 반영
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://todouser:todopass@db:5432/tododb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: postgres:15
    container_name: todo-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge