name: todo-app
region: sgp
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  name: web
  run_command: uvicorn main:app --host 0.0.0.0 --port 8000
  source_dir: /
databases:
- engine: MYSQL
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "8"